README.md, src/app.rs, src/bootstrap.rs, src/cmd.rs, src/control.rs, src/main.rs
Before this PR dynein saves detail of the currently using table in `~/.dynein/config.yml` file.
Now, `config.yml` only contains `using_region` and `using_table` to identify the target table, and a new file named `cache.yml` would store details of tables you have used so far.
```
$ cat ~/.dynein/config.yml
---
using_region: ap-northeast-1
using_table: books
$ cat ~/.dynein/cache.yml
---
tables:
us-east-1/Employee:
region: us-east-1
name: Employee
pk:
name: LoginAlias
kind: S
sk: ~
indexes: ~
mode: OnDemand
ap-northeast-1/books:
region: ap-northeast-1
name: books
pk:
name: isbn
kind: S
sk: ~
indexes: ~
mode: Provisioned
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> Separate dynein configuration from table schema cache

README.md, src/cmd.rs, src/control.rs, src/main.rs
Adding `dy admin update table` command to update existing table. For now it supports only following operations:
* changing mode (Provisioned/OnDemand)
* changing WCU/RCU of the base table
Example 1, switching from OnDemand mode to Provisioned mode with WCU/RCU specified. If you omit WCU/RCU, default value (5) would be used.
```
$ dy admin update table my_ondemand_table --mode provisioned --wcu 10 --rcu 25
```
Example 2, change only WCU of the Provisioned table.
```
$ dy admin update table my_provisioned_table --wcu 20
```
=> Implement 'admin update table' command to call UpdateTable API for existing tables. Only mode and CU for now.

Cargo.lock, Cargo.toml
*Issue #, if available:* release #1 and #2
Release version 0.1.1. Change log:
* [Separate dynein configuration from table schema cache by thash · Pull Request #1 · awslabs/dynein](https://github.com/awslabs/dynein/pull/1)
* [Implement 'admin update table' command to call UpdateTable API for existing tables. Only mode and CU for now. by thash · Pull Request #2 · awslabs/dynein](https://github.com/awslabs/dynein/pull/2)
=> Bump version to v0.1.1

.github/workflows/ci.yml, src/transfer.rs
`cargo clippy` can reveal a ton of warnings for things that can be
improved slightly and can be really beneficial while developing. Since
there were so many warnings, I felt it was best just to fix one file to
show how simple it is, and as to not cause any conflicts with on going
work.
The main warnings were (in this file):
- `.as_ref().map(|x| x.as_str())` -> `.as_deref()`
- `.push_str("\n")` -> `.push('\n')`
- `.len() {>,==,!=} 0` -> `{!}.is_empty()`
- unneeded return statements
- needlessly taken references
Very cool project, I am excited to use it.
<details>
```
warning: called `.as_ref().map(|x| x.as_str())` on an Option value. This can be done more directly by calling `format.as_deref()` instead
--> src/transfer.rs:59:36
|
59 |     let format_str: Option<&str> = …
```
=> run clippy on src/transfer.rs

.github/workflows/ci.yml, src/app.rs, src/batch.rs, src/bootstrap.rs, src/cmd.rs, src/control.rs, src/data.rs, src/main.rs, src/transfer.rs
*Issue #, if available:* #5 
Fix errors/warnings detected by `cargo clippy`.
At the same time comment out `cargo fmt` check for now, to see in github workflow if the clippy warnings are correctly fixed.
=> Deal with clippy warnings

src/app.rs
Before this change:
```
$ dy config dump
---
tables: ~
---
using_region: ~
using_table: ~
$ dy scan
thread 'main' panicked at 'tables should exist in cache', src/app.rs:461:76
```
After this change:
```
$ dy scan
To execute the command you must specify target table in one of following ways:
* [RECOMMENDED] $ dy use <your_table> ... save target table to use.
* Or, optionally you can pass --region and --table options to specify target for your commands. Refer --help for more information.
To find all tables in all regions, try:
* $ dy ls --all-regions
```
=> Show 'how to use' message when no table specified and no table cache are available

src/cmd.rs, src/control.rs, src/main.rs
Previously `dy desc` command only supports `--table (-t)` option to specify the target table.
Before this change:
```
$ dy desc Employee
error: Found argument 'Employee' which wasn't expected, or isn't valid in this context
USAGE:
dy desc [FLAGS] [OPTIONS]
```
After this change:
```
$ dy desc Employee
---
name: Employee
region: ap-northeast-1
status: ACTIVE
schema:
pk: LoginAlias (S)
sk: ~
mode: OnDemand
...
created_at: "2020-11-09T10:30:03+00:00"
```
Now you can use both ways (like `dy use`).
=> desc command supports both `dy desc mytbl` and `dy desc -t mytbl`

Cargo.lock, Cargo.toml, src/app.rs, src/cmd.rs, src/main.rs, src/shell.rs, tests/integration_test.rs
This patch adds a new shell flag namely `--shell` . When `--shell` is passed without subcommands, dynein starts an interactive shell session. In the shell session, you can input any dynein subcommands and built-in shell command (currently,  only `exit` is defined to exit the shell).
```
$ dy --shell
> list
hoge
fuga
piyo
> use fuga
Now you're using the table 'fuga' (ap-northeast-1);
> describe
---
name: fuga
region: ap-northeast-1
status: ACTIVE
....
> exit
```
As a bonus, you can  'script' the subcommands.
```console
$ cat script.txt
use fuga
describe
$ dy --shell < script.txt
...
```
How do you like this?
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> New feature: interactive shell

README.md
*Description of changes:* Without `--locked` option, the `cargo install` command will fail when dependencies have already been yanked.
=> [fix] add --locked option to the cargo install command

src/app.rs, src/cmd.rs, src/main.rs, tests/integration_test.rs
*Issue #21 , if available:*
It is sometimes used together with localstack, and is often started with a different port number.
So, I want to use a different port number from 8000.
added the `--port` option to change the port number.
=> Add port option for `--region local`

src/app.rs, src/batch.rs, src/bootstrap.rs, src/control.rs, src/data.rs, src/main.rs, src/transfer.rs
*Issue #29 , if available:* As the extern prelude is introduced in 2018 edition, `extern crate` is unidiomatic.
*Description of changes:* Removes `extern crate`.
=> [clean] clean up code to be compatible with 2018 edition

.github/workflows/build_binaries_on_new_releases.yml, README.md
N/A
This pull request adds a new GitHub Action workflow definition that builds dynein binaries automatically when a new release is published by maintainers.
Also, tiny modifications are made on README so that it matches the new build procedure.
=> Add a GitHub action to build dynein binaries on the new release created

src/cmd.rs, src/data.rs, src/main.rs, tests/integration_test.rs
This PR implement #20 request's ScanIndexForward support.
Add `--descending` options to support ScanIndexForward attribute.
API documentation available [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html).
=> Add descending option

Cargo.lock, Cargo.toml, tests/integration_test.rs
Previous `setup_with_port` actually fail to launch dynamodb-local.
This PR fixes broken `setup_with_port`. 
The main fix points are:
* `docker ps` was not able to filter intended container when old version docker is used. See [this PR](https://github.com/moby/moby/pull/40442).
* Variable `docker` was reused resulted in failure of `docker run`.
* We had to execute `cargo test` twice to pass tests.
=> Fix broken setup_with_port

src/app.rs
*Issue #18, if available:*
`dy list` doesn't work under the condition where `~/.dynein/cache.yml` contains at least one cached table and table name is not specified in both `~/.dynein/config.yml` and `--table` option.
`cached_using_table_schema()` (only used in `list_tables()`) returns `None` when table name is not specified in both `~/.dynein/config.yml` and `--table` option.
=> [fix] "dy ls" doesn't work when cache exists and table name is not specified

Cargo.lock, Cargo.toml, tests/integration_test.rs
This PR updates rusoto. We also should update tokio and reqwest which depends tokio.
- Bumps rusoto from 0.45.0 to 0.47.0.
- Bumps tokio from 0.2.16 to 1.14.0
- Bumps reqwest from 0.10.9 to 0.11.6
Related PRs are followings:
- https://github.com/awslabs/dynein/pull/44
- https://github.com/awslabs/dynein/pull/42
- https://github.com/awslabs/dynein/pull/39
- https://github.com/awslabs/dynein/pull/37
=> Bump rusoto to 0.47.0 and tokio to 1.14.0 and reqwest to 0.11.6

src/app.rs, src/main.rs
As `region` field in `Context` is not used anywhere, remove it.
=> remove unused region field in Context

.github/workflows/build_binaries_on_new_releases.yml
*Issue 95:*
Added the 'z' flag to tar command to gzip the archive, matching the `.tar.gz` naming of the artifact file.
Alternatively, you could drop the `gz` and just upload the file as tar.
=> Adds zip flag to tar command for artifact build, closing #95

src/app.rs, tests/integration_test.rs
Program now checks environment variable DYNEIN_CONFIG_DIR and if set, uses that as the location to store the configuration files
*Issue #, if available:* 106
*Description of changes:* Program now checks environment variable DYNEIN_CONFIG_DIR and if set, uses that as the location to store the configuration files. The environment variable's name is in a global variable.
=> Allow users to change location of config files with env var DYNEIN_CONFIG_DIR

src/bootstrap.rs
N/A
ZipError occur when downloading sample is failed that it is not helpful to investigate what is happened.
```
Temporarily downloading sample data from https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/samples/sampledata.zip
Error: ZipError(InvalidArchive("Could not find central directory end"))
```
We can use `error_for_status` to detect error from target URL such as 403 as follows.
```
Temporarily downloading sample data from https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/samples/sampledata.zip
Error: ReqwestError(reqwest::Error { kind: Status(403), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("docs.aws.amazon.com")), port: None, path: …
```
=> refactor: return error when download is failed

.pre-commit-config.yaml, README.md
N/A
We can easily forget to run `cargo fmt --all` and `cargo clippy -- -D warnings`. Although #117 enforces success of those commands upon pull requests, local running is useful for daily development.
This pull request adds configuration for [`pre-commit`](https://pre-commit.com/) to execute above commands on pre-commit hook.
FYI: [smithy](https://github.com/awslabs/smithy-rs) uses `pre-commit`.
=> chore: Introduce pre-commit

.github/workflows/ci.yml
N/A
Commit 5db95228a212 replaced `push` event with `pull_request` event, but the `push` event is still requried to run CI on top of the main branch after merging PRs.
=> chore: Restore push event

src/bootstrap.rs
Fix #103
If user_agent is not specified, the server response 403 error as follows.
```
$ RUST_LOG=debug cargo run -- bootstrap
...
[2023-05-12T17:38:28Z DEBUG dy::bootstrap] temporary download & unzip directory: TempDir { path: "/var/folders/ys/zr1z7ql10kvcp8v3g2zbyp080000gs/T/.tmpvtdrOq" }
Temporarily downloading sample data from https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/samples/sampledata.zip
[2023-05-12T17:38:28Z DEBUG reqwest::connect] starting new connection: https://docs.aws.amazon.com/
Error: ReqwestError(reqwest::Error { kind: Status(403), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("docs.aws.amazon.com")), port: None, path: …
```
=> fix: specify user_agent when download sample.

.pre-commit-config.yaml
N/A
Add `tests/cmd` directory into the exclude list for pre-commit hooks to prevent breaking tests.
=> chore: exclude markdown files in cmd directory

.github/workflows/ci.yml, tests/integration_test.rs
*Issue #56, if available:*
If you specify `DYNEIN_TEST_NO_DOCKER_SETUP=true` on environment variable, `cargo test` does not start docker container on testing.
=> Add a flag DYNEIN_TEST_NO_DOCKER_SETUP to prevent launching docker container on testing

src/app.rs, src/batch.rs, src/bootstrap.rs, src/control.rs, src/data.rs, src/transfer.rs
N/A
- Using wildcard import is hard to understand what kind of struct is used in general. Also the crate has same name struct with AWS SDK for Rust. It causes to take time to migrate it.
- move describe_table_api to control
=> refactor: refactor some points related to rusoto_dynamodb

Cargo.lock, Cargo.toml, README.md, src/data.rs, src/expression.pest, src/main.rs, src/parser.rs
* #92
* #82
This PR implements correct parsing for `UpdateItem` API (`upd` command) using [pest](https://pest.rs/). This also contains the following feature enhancements and bug fixes.
* Support a binary type.
* Support a single quotes for a string type.
* Support list_append and if_not_exists function.
* Support spcifying a list element as a path.
* No longer fail when a expression containing hyphens, commas, indexing, etc.
But, it introduces a breaking change.
* A list type is no longer classified automatically based on its element type. The current behavior is described in [dispatch_jsonvalue_to_attrval function](https://github.com/awslabs/dynein/blob/5eb664559bee22f5e4f7931ed5310d47d9d68f36/src/data.rs#L828-L845)
By submitting this …
=> implement correct parsing for UpdateItem API

README.md
N/A
This pull request removes the duplicate explanation for the `Quoting a Path of an Attribute` section from `README.md`.
=> docs: remove duplicate explanation for quoting path

Cargo.lock, Cargo.toml, tests/bwrite.rs, tests/get.rs, tests/query.rs, tests/resources/test_batch_write.json, tests/scan.rs, tests/util/mod.rs
N/A
- I have added the test for `dy get` because the test is nothing
- add `create_temporary_table` function: generate random table name and output the name into stdout. So if the test is failed, we can check the name on the result
=> test: add integration test for get

README.md, src/batch.rs, src/bootstrap.rs, src/cmd.rs, src/data.rs, src/main.rs, src/transfer.rs, tests/cmd/import.md
BREAKING CHANGE: import command no longer inferences set types without `--enable-set-inference`
* #139
* Partial solution for #66
This commit introduces the `--enable-set-inference` flag to the import command. Without this option, the import command no longer infers set types like string-set and number-set. To achieve the same behavior, you should provide the `--enable-set-inference` option. This resolves #139. Also, this can be considered the one solution for the #66 problem.
=> feat!: Add --enable-set-inference flag to import

Cargo.lock, Cargo.toml, src/transfer.rs
Partial implementation for #91.
This pull request aims to partially resolve #91 by providing the current number of completed items. The calculation for item size requires additional work and depends on the SDK, which is currently undergoing changes. Therefore, I implemented this without the information on sizes.
=> feat: show the number of processed items in import/export

tests/bwrite.rs, tests/del.rs, tests/get.rs, tests/query.rs, tests/scan.rs, tests/util/mod.rs
#143 
I have added the test for `dy del` because the test is nothing.
=> test: add integration test for del

tests/desc.rs
#143 
I have added the test for `dy desc` because the test is nothing.
=> test: add integration test for desc

tests/list.rs
https://github.com/awslabs/dynein/issues/143
I have added the test for dy list command. 
=> test: add integration test for list

tests/admin_desc.rs
#143 
I have added the test for `dy admin desc`.
=> test: add integration test for admin desc

tests/admin.rs, tests/admin_desc.rs, tests/bootstrap.rs, tests/bwrite.rs, tests/del.rs, tests/desc.rs, tests/get.rs, tests/list.rs, tests/query.rs, tests/scan.rs, tests/shell.rs, tests/util/mod.rs
#157 #169 
- `TestManager.command` return `Command::cargo_bin` as wrapper.
- Table which is created by `TestManager.create_temporary_table` is deleted automatically.
- add `util::setup_with_lock` to ensure that a test is the only one at a time.
- test_admin_desc_all_tables: when the flag `--all-tables` is specified, dynein call ListTable and DescribeTable. It will cause not found error because the table is deleted by other test.
- test_desc_all_tables: same situation with test_admin_desc_all_tables
- test_list_table_with_no_table: if other test create table, this test is failed because the test check `No table in this region.`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> test: improve setup

src/app.rs, tests/auxiliary.rs, tests/util/mod.rs
#172 
We use temp file to generate default config. Because while fs::write is writing the contents to default config path, serde_yaml::from_str return EndOfStream.
=> fix: use temp file to write config

README.md, docs/format.md, src/data.rs, src/expression.pest, src/parser.rs
Solve #162
Introduce pest parsing into put command. This commit adds new features and breaking changes but not limited to,
* Support binary types.
* Support single quotes for a string type.
* Support explicit set types.
However, it no longer supports the inference of set type when using `[elem]` because we can now specify set type explicitly using `<<elem>>` literal.
BREKING CHANGE: put command no longer infers a set type.
=> implement new parsing into put command

src/cmd.rs, src/main.rs, tests/apply.rs
*Issue https://github.com/awslabs/dynein/issues/155#issuecomment-1701326714
During development, to eliminate the impact on users, ensure that apply only works when `--dev` is added.
```zsh
$ dy admin apply
not yet implemented
$ dy admin apply --dev
(something happen)
```
Now, `dy admin apply --dev` causes panic.
```zsh
~/Desktop/dynein
$ ./target/release/dy admin apply
not yet implemented
~/Desktop/dynein
$ ./target/release/dy admin apply --dev
thread 'main' panicked at 'not yet implemented', src/main.rs:89:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> feat: add flag for developing `dy admin apply`

src/bootstrap.rs
Print region where table already exists for making easier to debug why skip to create new table
ref:
https://github.com/awslabs/dynein/blob/d546a36899bd7f765cb57b7c3c2b7139458b635f/src/bootstrap.rs#L315-L322
=> chore(bootstrap): print region where table already exists

.github/workflows/bot.yml, .github/workflows/build_binaries_on_new_releases.yml, .github/workflows/ci.yml, README.md, tests/cli_tests.rs, tests/cmd_windows/admin.md, tests/cmd_windows/backup.md, tests/cmd_windows/bootstrap.md, tests/cmd_windows/bwrite.md, tests/cmd_windows/config.md, tests/cmd_windows/del.md, tests/cmd_windows/desc.md, tests/cmd_windows/export.md, tests/cmd_windows/get.md, tests/cmd_windows/help.md, tests/cmd_windows/import.md, tests/cmd_windows/list.md, tests/cmd_windows/put.md, tests/cmd_windows/query.md, tests/cmd_windows/restore.md, tests/cmd_windows/scan.md, tests/cmd_windows/upd.md, tests/cmd_windows/use.md
#159 
This PR fixes the issue of test failures on Windows by introducing separate snapshots for Windows.
=> test: fix test failures on Windows

Cargo.lock, Cargo.toml, src/batch.rs, tests/bwrite.rs, tests/resources/test_batch_write.json
#168
This PR adds support for Binary data types (B, BS) to`bwrite` command. 
=> feat: add binary data type support to `bwrite` command

.github/workflows/bot.yml, README.md
Currently, the snapshot bot does not work correctly.
https://github.com/awslabs/dynein/actions/runs/6730473189.
This pull request will fix the failure to generate a snapshot. Due to permission restriction, the bot only generates a diff. It means that the application of patches becomes the duty of requesters of pull requests.
The following is the example behavior of the bot.
https://github.com/StoneDot/dynein/pull/17#issuecomment-1794211433
=> chore: fix snapshot bot

tests/desc.rs
N/A
Improved the integration test for desc to align with #161, which tests two tables.
=> test: improve integration test for desc

tests/config.rs, tests/util/mod.rs
#143 
I have added the test for `dy config` because the test is nothing.
=> test: add integration test for config

Cargo.lock, Cargo.toml, src/shell.rs
N/A
This pull request replaces the unmaintained `atty` with `std::io::IsTerminal.`
=> refactor: remove atty dependency

.github/workflows/ci.yml, README.md, src/batch.rs, src/bootstrap.rs, src/cmd.rs, src/data.rs, src/main.rs, src/parser.rs, tests/bwrite.rs, tests/cmd/bwrite.md, tests/cmd_windows/bwrite.md, tests/resources/test_batch_write_delete.json, tests/resources/test_batch_write_put.json, tests/resources/test_batch_write_put_delete.json, tests/resources/test_batch_write_put_delete_multiple_tables.json, tests/resources/test_batch_write_put_output.json, tests/util/mod.rs
#164
Introduce new options into put command. This commit adds new command options, `--put` and `--del`.
```
dy bwrite --put '{Dynein format}' --put '{Dynein format}' --del '{Dynein format}'
```
=> feat: implement new options into bwrite command

README.md, docs/query.md, src/app.rs, src/cmd.rs, src/data.rs, src/expression.pest, src/main.rs, src/parser.rs, tests/cmd/query.md, tests/cmd_windows/query.md, tests/config.rs, tests/query.rs
Implement #163
This PR improves the parsing for the sort key condition. The current implementation cannot handle the sort key containing spaces. This PR fixes this and provides a way that is compatible with the dynein format.
Improvements contain the following features:
* Introduce two formats for --sort-key: strict format and non-strict.
* You can now query any condition DynamoDB supports using the strict format.
* The non-strict format allows the user less typing and types agnostic input.
* The non-strict format retains the same experience as much as possible.
* Add --strict and --non-strict options to change the usage of non-strict.
* Add configuration option and query.strict_mode to change the default mode.
BREAKING CHANGE: Parsing …
=> feat!: improve query to support dynein format

Cargo.lock, Cargo.toml
N/A
This pull request deletes `build-dependencies`, which is no longer necessary.
=> chore: remove build-dependencies

.github/workflows/audit.yml
Implement #209 
This pull request adds the GitHub workflow to execute `cargo audit` at 08:43 JST everyday. We exclude some checks because they are known in our team and we are working on them. Additionally, these issue does not affect users.
An example execution: https://github.com/StoneDot/dynein/actions/runs/8848193297/job/24297549653
=> chore: add an GitHub workflow for daily audit

.github/workflows/build_binaries_on_new_releases.yml
*Issue: #219*
This pull request adds a new step to the CI that generates checksums for the Windows executable files produced during the build process
=> chore: add generating SHA256 checksum for Windows assets

Cargo.lock, Cargo.toml, src/app.rs, src/batch.rs, tests/config.rs
add exponential backoff retry for ProvisionedThroughputExceeded / ThrottlingException / InternalServerError
#195 
Added the configuration to retry `batch_write_item_api`.
Since `retry_batch_write_item` is optional, it can be undefined. 
In this case, no retry is performed.
dy config dump
```
---
tables: ~
---
using_region: ~
using_table: ~
using_port: ~
retry: ~
```
```
---
tables: ~
---
using_region: ~
using_table: ~
using_port: ~
retry:
default:
initial_backoff: ~
max_backoff:
secs: 10
nanos: 0
max_attempts: 20
batch_write_item: ~
```
Output retry logs with warn level. …
=> feat: add exponential backoff retry for ProvisionedThroughputExceeded / ThrottlingException / InternalServerError

tests/scan.rs, tests/util/mod.rs
#143
This pull request adds integration tests for scan command.
=> test: add integration tests for scan

tests/bootstrap.rs, tests/export.rs, tests/get.rs, tests/util/mod.rs
#143
I have added the test for `dy export` because the test is nothing.
=> test: add integration test for export

tests/restore.rs
#143
This pull request adds an integration test for `restore` command. Please note that we cannot conduct a full test for this feature currently because the DynamoDB local does not support the backup feature.
=> test: add integration test for restore

src/cmd.rs
part of #109 
`parse_args` is used by shell in order to run command. The function is depend on old clap so we need to rewrite it when we use new clap. So we add test to ensure that the function is consistent.
https://github.com/awslabs/dynein/blob/33a573892de893b923efabad36fe177b029b773a/src/cmd.rs#L65-L78
=> test: add parse_args test

tests/backup.rs
#143
This pull request adds an integration test for `backup` command. In this PR, we cannot conduct full tests as well as restore https://github.com/awslabs/dynein/pull/233.
=> test: add integration test for backup

tests/import.rs
#143
This pull request adds integration tests for `import` command.
=> test: add integration tests for import

tests/admin_desc.rs, tests/admin_list.rs, tests/bwrite.rs, tests/del.rs, tests/desc.rs, tests/get.rs, tests/list.rs, tests/query.rs, tests/scan.rs, tests/upd.rs
Related to #143
This pull request adds tests for command aliases, `dy info`, `dy q`, and so on.
=> test: add integration test for command aliases

tests/admin_delete.rs, tests/util/mod.rs
#143 
I have added the test for dy admin delete command.
=> test: Integration test admin delete

tests/bwrite.rs, tests/scan.rs
N/A
Some tests are using `output()` which don't check whether the command is succeeded. In order to check succeeded, we need to use `assert().success()` instead.
=> test: use assert to check whether the command is succeeded

Cargo.lock, Cargo.toml, src/app.rs
N/A
This pull request changes a dependency from `dirs` to `home`. Currently, `dirs` is an overkill crate for our project.
This is breaking change because two crates provide different behavior.
* https://docs.rs/dirs/latest/dirs/fn.home_dir.html
* https://docs.rs/home/latest/home/fn.home_dir.html
=> chore!: change a dependency from dirs to home

src/cmd.rs, tests/cmd/admin.md, tests/cmd_windows/admin.md
N/A
We provide `-y` to delete table for usability. A lot of CLI provide `-y` or `--yes` to get confirmation.
=> feat: add -y as short yes to delete table

src/transfer.rs, tests/export.rs
*Issue #152*
Empty array in function `connectable_json` came on one line even not in compact format.
This PR tests this case and act acordingly 
=> fix(export): empty array is on one line fix #152

Cargo.lock, Cargo.toml, src/bootstrap.rs
N/A
We used zip crate to extract zip file of bootstrap previously but we have local data by #153. So we don't depend on zip crate.
=> chore: remove zip dependency

Cargo.lock, Cargo.toml, src/bootstrap.rs
#248
This pull request removes the dependency on `reqwest`. This clean-up enables the removal of the runtime dependency on OpenSSL and improves the binary's portability.
=> chore: remove reqwest dependency

src/app.rs, src/batch.rs, src/bootstrap.rs, src/control.rs, src/data.rs, src/ddb/key.rs, src/ddb/table.rs, src/main.rs, src/transfer.rs
This PR is related to #6.
This PR reduces the use of `clone`.
There are primary and accompanying goals such as:
* Reduce `clone` to improve performance.
* Currently, there is no good way to update the context cache without quitting the program. It causes an incoherent cache on shell mode. Mutable reference is a way to solve this problem. As of this pull request, we have not introduced a cache update.
* Give future ability into context to hold another cache like "item cache," which is required to implement completions.
I welcome the discussion to achieve the above goals.
=> refactor: reduce clone usage

src/app.rs, src/bootstrap.rs, src/control.rs, src/data.rs, tests/backup.rs, tests/restore.rs
fix #247. In this PR, we introduce useful error message.
```rust
[2024-06-17T15:29:52Z ERROR dy::control] service error occurred: ErrorMetadata { code: Some("ValidationException"), message: Some("1 validation error detected: Value 'a' at 'tableName' failed to satisfy constraint: Member must have length greater than or equal to 3"), extras: Some({"aws_request_id": "xxx"}) }
```
```rust
[2024-06-17T15:28:16Z ERROR dy::control] an error occurred: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: InvalidConfiguration(InvalidConfiguration { source: "ProfileFile provider could not be built: profile `a` was not defined: could not find source profile a referenced from the root profile" }), connection: Unknown } })
```
Best way to show …
=> chore: handle SdkError to show error message

Cargo.lock, Cargo.toml
N/A
bytes for 1.6.0 is yanked.
https://crates.io/crates/bytes/1.6.0
=> chore: update bytes to 1.6.1

Cargo.lock, Cargo.toml
N/A
The 0.3.30 of futures-util is yanked.
https://crates.io/crates/futures-util/0.3.30
=> chore: update futures to 0.3.31

tests/bwrite.rs, tests/del.rs, tests/export.rs, tests/get.rs, tests/put.rs, tests/query.rs, tests/use.rs
#238 
This PR addresses the issue raised in #238 by removing the unnecessary use of `vec!` macro when calling　`create_temporary_table_with_items`.
=> test: remove unnecessary vec! from create_temporary_table_with_items

.github/workflows/ci.yml, tests/util/mod.rs
N/A
Currently, the `cargo test` command uses a default credential chain to determine an AWS credential. However, it should use a dummy credential instead because an actual credential may change the production environment. Switching the default credential to a dummy credential also mitigates the pain when executing a `cargo test` that may require setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
=> test: use dummy credential when executing tests
