awslabs/dynein

Cargo.lock, Cargo.toml
=> Bump version to v0.1.2

.github/workflows/ci.yml, src/app.rs, src/batch.rs, src/bootstrap.rs, src/cmd.rs, src/control.rs, src/data.rs, src/main.rs, src/transfer.rs, tests/integration_test.rs
Basically the PR contains only cosmetic changes. This PR would format entire code using [rustfmt](https://github.com/rust-lang/rustfmt) and add `cargo fmt --all -- check` action in GitHub workflow.
=> apply cargo fmt

src/app.rs, src/shell.rs
After merging #13 I saw some clippy warnings, which broke GitHub CI workflow. This PR would fix them.
In future it's better to check them for incoming PRs automatically.
=> resolve clippy warnings

src/app.rs, tests/integration_test.rs
* cargo clippy & cargo fmt for #22 
=> cargo clippy & cargo fmt for #22

src/control.rs
*Issue #53, if available:*
`dy ls --all-regions` fails when using a table in local region, because EC2 DescribeRegions API is not available for local region.
When using a table in local region,
- issues EC2 DescribeRegions API request to us-east-1 region.
- lists tables for local region in addition.
=> [fix] handles local region in "dy ls --all-regions".

src/control.rs
Reverts awslabs/dynein#54
I missed to check to `cargo fmt` before merge. So, I asked him to re-check.
=> Revert "[fix] handles local region in "dy ls --all-regions"."

src/app.rs, src/batch.rs, src/bootstrap.rs, src/data.rs, src/shell.rs, tests/integration_test.rs
*Description of changes:* Some minor clippy-assisted cleanups.
=> Fix clippy warnings

Cargo.lock, Cargo.toml
=> Bump version to v0.2.1

.github/workflows/ci.yml
N/A
- show result of clippy: [sample commit](https://github.com/awslabs/dynein/commit/278e2998f2edb7f953cd98269a2126b8dc18f8fb)
- add cache to improve CI performance: refer to [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust/blob/2ebc092a0372b5f1508b26845c0cf88f537d29b7/.github/workflows/ci.yaml#L45-L48)
=> chore: improve workflows

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, tests/cli_tests.rs, tests/cmd/admin.md, tests/cmd/backup.md, tests/cmd/bootstrap.md, tests/cmd/bwrite.md, tests/cmd/config.md, tests/cmd/del.md, tests/cmd/desc.md, tests/cmd/export.md, tests/cmd/get.md, tests/cmd/help.md, tests/cmd/import.md, tests/cmd/list.md, tests/cmd/put.md, tests/cmd/query.md, tests/cmd/restore.md, tests/cmd/scan.md, tests/cmd/upd.md, tests/cmd/use.md
N/A
We need to check compatibility of CLI.
- use [trycmd](https://crates.io/crates/trycmd) to conduct snapshot testing
- run snapshot testing on GitHub Actions
- add snapshot for current CLI manually
=> chore: add trycmd to conduct snapshot testing for CLI

.github/workflows/ci.yml, tests/integration_test.rs
Add ignore on some tests once because the tests need Docker.
ref: #55 
We need to check that all of commits is passed for test before merge. But we cannot run some tests on integration_test.rs because it depends on Docker so I add ignore for now.
=> test: run unit tests on CI

README.md, src/data.rs
#82 #92 #114 
We need to write test code for compatibility also we need to know known issues.
=> test: add generate_update_expressions test

.github/workflows/ci.yml, tests/integration_test.rs
ref: #55
We need to check that all of commits is passed for test before merge.
=> chore: run integration tests on CI

README.md
=> docs: add link to Bootstrap command

tests/desc.rs
N/A
This PR fixes the current CI failure.
https://github.com/awslabs/dynein/actions/runs/5964279563/job/16179140365
=> test: fix broken tests for desc command

docs/format.md, src/expression.pest, src/parser.rs
#176
This PR enables dynein to parse all valid JSON, which is required by RFC 8259. 
=> feat!: improve json compatibility

tests/list.rs
#143 
I have add the test that `dy list` shows current table after running `dy use`
=> test: show current table in list

README.md, src/bootstrap.rs
`https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.*.html` has moved to https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.html.
Movie sample data is not used in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.html.
```zsh
$ curl https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.02.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.html">here</a>.</p>
</body></html>
$ curl …
```
=> docs(bootstrap): change link to Movie sample data

.github/workflows/bot.yml, .github/workflows/build_binaries_on_new_releases.yml, .github/workflows/ci.yml
N/A
This pull request eliminates deprecated actions and updates action versions. Additionally, this fixes the current CI errors.
I have a plan to change the holistic change for `bot.yml` in another pull request. Thus, I do not include the change for `bot.yml` at this time. However, changing the version of `Swatinem/rust-cache` is included to maintain the version consistency for the cache.
I tested this PR on [my repository](https://github.com/StoneDot/dynein/actions).
=> chore: update CI/CD to eliminate deprecated actions

CONTRIBUTING.md, README.md
N/A
Add a section `CONTRIBUTING.md` describing the prerequisite for a pull request. It is necessary to prevent the inadvertent committing of credentials into the repository.
Besides, the some information related to contribution is moved to `CONTRIBUTING.md`.
=> chore: add prerequisite of git secrets

.github/workflows/ci.yml
Implement #210
This PR added a GitHub workflow job to execute a cargo audit when a PR is submitted, in order to maintain our code health.
An example execution:
Success: https://github.com/tmyoda/dynein/actions/runs/8846880245
Failed: https://github.com/tmyoda/dynein/actions/runs/8847001630
=> chore: add GitHub workflow for PR audit

Cargo.lock, Cargo.toml, src/batch.rs, src/transfer.rs, tests/admin_desc.rs, tests/config.rs, tests/desc.rs
N/A
This pull request updates dependencies including major changes. It also includes breaking changes of the yaml format especially for `null` and use of `---`. Besides, we change the error messages to reflect the change of the dependency.
=> chore!: update deps including major changes

.github/workflows/ci.yml
#206
This PR adds a GitHub workflow to detect credential disclosures using `trufflehog`.
An example execution:
test PR: https://github.com/tmyoda/dynein/pull/6
Execution logs: https://github.com/tmyoda/dynein/actions/runs/8851931664/job/24309537599
=> chore: add a GitHub workflow for PRs to detect credential disclosures

tests/admin_update.rs
#143
This pull request adds integration tests for `admin update` command.
=> test: add integration tests for admin update

tests/config.rs, tests/query.rs, tests/util/mod.rs
Implement #199
Sub task of #143
This pull request adds integration tests for query command. Additionally, this pull request introduces a separate configuration directory for each test.
=> test: add integration tests for query

tests/get.rs, tests/use.rs, tests/util/mod.rs
#143
This pull request adds integration tests for `use` command.
=> test: add integration tests for use

tests/put.rs
#143 
This pull request adds integration tests for put command.
=> test: add integration tests for put

.github/workflows/bot.yml
N/A
This pull request improve the bot permissions and enhance the safety.
Test execution: https://github.com/StoneDot/dynein/pull/17#issuecomment-2147115756
=> chore: improve bot permission

Cargo.lock, Cargo.toml
N/A
This pull request bump version into v0.3.0.
=> Bump version into v0.3.0

.github/workflows/ci.yml
N/A
This PR enables CI/CD in release branches and release tags to ensure their quality.
**Sample executions**
* Tag: [v0.3.0](https://github.com/StoneDot/dynein/actions/runs/9597579288)
* Branch: [release-0.3](https://github.com/StoneDot/dynein/actions/runs/9597544469)
=> chore: execute CI/CD on releases

src/data.rs
There's a bug when the column data is NULL.
=> fix: Specified attribute not found in the item error.
